# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 17, 21 ]
        exclude:
          - os: ubuntu-latest
            java: 17
          - os: macos-latest
            java: 21
          - os: windows-latest
            java: 21

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: xvfb-run -a mvn -B verify
      if: ${{ runner.os == 'Linux' }}
    - name: Build with Maven
      run: mvn -B verify
      if: ${{ runner.os != 'Linux' }}
